namespace FlameCsv.Binding.Attributes;

/// <summary>
/// Binds <see cref="MemberName"/> to CSV field at <see cref="Index"/>.
/// Can be used when <see cref="CsvIndexAttribute"/> cannot be used, e.g. on autogenerated partial classes.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true)]
public sealed class CsvIndexTargetAttribute : Attribute, ICsvBindingAttribute
{
    /// <summary>CSV field index.</summary>
    public int Index { get; }

    /// <summary>Name of the property or field.</summary>
    public string MemberName { get; }

    /// <inheritdoc cref="ICsvBindingAttribute.Scope"/>
    public CsvBindingScope Scope { get; set; }

    /// <inheritdoc cref="CsvIndexTargetAttribute"/>
    /// <param name="index">CSV field index</param>
    /// <param name="memberName">Name of the property or field</param>
    public CsvIndexTargetAttribute(
        int index,
        string memberName)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(index, 0);
        ArgumentException.ThrowIfNullOrWhiteSpace(memberName);
        Index = index;
        MemberName = memberName.Trim();
    }
}
