/// <auto-generated />
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;

internal interface ISimdVector<T, TVector>
    where T : unmanaged, IBinaryInteger<T>
    where TVector : struct, ISimdVector<T, TVector>
{
    static abstract bool IsSupported { get; }
    static abstract int Count { get; }
    static abstract TVector Zero { get; }
    static abstract TVector Equals(TVector left, TVector right);
    static abstract TVector Create(T value);
    static abstract TVector LoadUnsafe(ref readonly T source, nuint offset);
    static abstract TVector Or(TVector left, TVector right);
    [JetBrains.Annotations.Pure] nuint ExtractMostSignificantBits();
}

[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
internal readonly struct Vec64<T>(Vector64<T> value) : ISimdVector<T, Vec64<T>> where T : unmanaged, IBinaryInteger<T>
{
    private readonly Vector64<T> _value = value;

    public static bool IsSupported
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
            => Vector64<T>.IsSupported
#if RELEASE
            && Vector64.IsHardwareAccelerated
#endif
        ;
    }

    public static int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Vector64<T>.Count;
    }

    public static Vec64<T> Zero
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Vector64<T>.Zero;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec64<T> Equals(Vec64<T> left, Vec64<T> right) => Vector64.Equals(left._value, right._value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec64<T> Create(T value) => Vector64.Create(value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec64<T> LoadUnsafe(ref readonly T source, nuint offset) => Vector64.LoadUnsafe(in source, offset);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec64<T> Or(Vec64<T> left, Vec64<T> right) => Vector64.BitwiseOr(left._value, right._value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public nuint ExtractMostSignificantBits() => nuint.CreateSaturating(_value.ExtractMostSignificantBits());

    public static implicit operator Vec64<T>(Vector64<T> value) => new Vec64<T>(value);

    public override string ToString() => _value.ToString();
    public override bool Equals(object obj) => throw new NotSupportedException();
    public override int GetHashCode() => throw new NotSupportedException();
}

[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
internal readonly struct Vec128<T>(Vector128<T> value) : ISimdVector<T, Vec128<T>> where T : unmanaged, IBinaryInteger<T>
{
    private readonly Vector128<T> _value = value;

    public static bool IsSupported
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
            => Vector128<T>.IsSupported
#if RELEASE
            && Vector128.IsHardwareAccelerated
#endif
        ;
    }

    public static int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Vector128<T>.Count;
    }

    public static Vec128<T> Zero
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Vector128<T>.Zero;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec128<T> Equals(Vec128<T> left, Vec128<T> right) => Vector128.Equals(left._value, right._value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec128<T> Create(T value) => Vector128.Create(value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec128<T> LoadUnsafe(ref readonly T source, nuint offset) => Vector128.LoadUnsafe(in source, offset);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec128<T> Or(Vec128<T> left, Vec128<T> right) => Vector128.BitwiseOr(left._value, right._value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public nuint ExtractMostSignificantBits() => nuint.CreateSaturating(_value.ExtractMostSignificantBits());

    public static implicit operator Vec128<T>(Vector128<T> value) => new Vec128<T>(value);

    public override string ToString() => _value.ToString();
    public override bool Equals(object obj) => throw new NotSupportedException();
    public override int GetHashCode() => throw new NotSupportedException();
}

[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
internal readonly struct Vec256<T>(Vector256<T> value) : ISimdVector<T, Vec256<T>> where T : unmanaged, IBinaryInteger<T>
{
    private readonly Vector256<T> _value = value;

    public static bool IsSupported
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
            => Vector256<T>.IsSupported
#if RELEASE
            && Vector256.IsHardwareAccelerated
#endif
        ;
    }

    public static int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Vector256<T>.Count;
    }

    public static Vec256<T> Zero
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Vector256<T>.Zero;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec256<T> Equals(Vec256<T> left, Vec256<T> right) => Vector256.Equals(left._value, right._value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec256<T> Create(T value) => Vector256.Create(value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec256<T> LoadUnsafe(ref readonly T source, nuint offset) => Vector256.LoadUnsafe(in source, offset);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec256<T> Or(Vec256<T> left, Vec256<T> right) => Vector256.BitwiseOr(left._value, right._value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public nuint ExtractMostSignificantBits() => nuint.CreateSaturating(_value.ExtractMostSignificantBits());

    public static implicit operator Vec256<T>(Vector256<T> value) => new Vec256<T>(value);

    public override string ToString() => _value.ToString();
    public override bool Equals(object obj) => throw new NotSupportedException();
    public override int GetHashCode() => throw new NotSupportedException();
}

[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
internal readonly struct Vec512<T>(Vector512<T> value) : ISimdVector<T, Vec512<T>> where T : unmanaged, IBinaryInteger<T>
{
    private readonly Vector512<T> _value = value;

    public static bool IsSupported
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
            => Vector512<T>.IsSupported
#if RELEASE
            && Vector512.IsHardwareAccelerated
#endif
        ;
    }

    public static int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Vector512<T>.Count;
    }

    public static Vec512<T> Zero
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Vector512<T>.Zero;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec512<T> Equals(Vec512<T> left, Vec512<T> right) => Vector512.Equals(left._value, right._value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec512<T> Create(T value) => Vector512.Create(value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec512<T> LoadUnsafe(ref readonly T source, nuint offset) => Vector512.LoadUnsafe(in source, offset);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec512<T> Or(Vec512<T> left, Vec512<T> right) => Vector512.BitwiseOr(left._value, right._value);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public nuint ExtractMostSignificantBits() => nuint.CreateSaturating(_value.ExtractMostSignificantBits());

    public static implicit operator Vec512<T>(Vector512<T> value) => new Vec512<T>(value);

    public override string ToString() => _value.ToString();
    public override bool Equals(object obj) => throw new NotSupportedException();
    public override int GetHashCode() => throw new NotSupportedException();
}
