// <auto-generated />
#nullable enable
using System.Text;
using System.Runtime.CompilerServices;
using FlameCsv.Binding;
using FlameCsv.IO;
using FlameCsv.IO.Internal;
using FlameCsv.ParallelUtils;

namespace FlameCsv;

static partial class CsvParallel
{
    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="csv"/>.
    /// </summary>
    /// <param name="csv">CSV data to read</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadAsync<[DAM(Messages.ReflectionBound)] TValue>(
        ReadOnlyMemory<char> csv,
        CsvOptions<char>? options = null,
        CsvParallelOptions parallelOptions = default
    )
    {
        return AsAsyncEnumerableCore(
            ParallelReader.Create(csv, options ?? CsvOptions<char>.Default),
            ValueProducer<char, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="csv"/>.
    /// </summary>
    /// <param name="csv">CSV data to read</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IEnumerable<ReadOnlySpan<TValue>> Read<[DAM(Messages.ReflectionBound)] TValue>(
        ReadOnlyMemory<char> csv,
        CsvOptions<char>? options = null,
        CsvParallelOptions parallelOptions = default
    )
    {
        return AsEnumerableCore(
            ParallelReader.Create(csv, options ?? CsvOptions<char>.Default),
            ValueProducer<char, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="path"/>.
    /// </summary>
    /// <param name="path">TextReader to read the CSV data from</param>
    /// <param name="encoding">Encoding to use, defaults to UTF8</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadFromFileAsync<[DAM(Messages.ReflectionBound)] TValue>(
        string path,
        Encoding? encoding = null,
        CsvOptions<char>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        ioOptions = ioOptions.ForFileIO();
        return AsAsyncEnumerableCore(
            ParallelReader.Create(CsvReader.GetFileStream(path, isAsync: true, in ioOptions), encoding, options ?? CsvOptions<char>.Default, ioOptions),
            ValueProducer<char, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="reader"/>.
    /// </summary>
    /// <param name="reader">TextReader to read the CSV data from</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadAsync<[DAM(Messages.ReflectionBound)] TValue>(
        TextReader reader,
        CsvOptions<char>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(reader);
        return AsAsyncEnumerableCore(
            ParallelReader.Create(reader, options ?? CsvOptions<char>.Default, ioOptions),
            ValueProducer<char, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="path"/>.
    /// </summary>
    /// <param name="path">TextReader to read the CSV data from</param>
    /// <param name="encoding">Encoding to use, defaults to UTF8</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IEnumerable<ReadOnlySpan<TValue>> ReadFromFile<[DAM(Messages.ReflectionBound)] TValue>(
        string path,
        Encoding? encoding = null,
        CsvOptions<char>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        ioOptions = ioOptions.ForFileIO();
        return AsEnumerableCore(
            ParallelReader.Create(CsvReader.GetFileStream(path, isAsync: false, in ioOptions), encoding, options ?? CsvOptions<char>.Default, ioOptions),
            ValueProducer<char, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="reader"/>.
    /// </summary>
    /// <param name="reader">TextReader to read the CSV data from</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IEnumerable<ReadOnlySpan<TValue>> Read<[DAM(Messages.ReflectionBound)] TValue>(
        TextReader reader,
        CsvOptions<char>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(reader);
        return AsEnumerableCore(
            ParallelReader.Create(reader, options ?? CsvOptions<char>.Default, ioOptions),
            ValueProducer<char, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="csv"/>.
    /// </summary>
    /// <param name="csv">CSV data to read</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadAsync<[DAM(Messages.ReflectionBound)] TValue>(
        ReadOnlyMemory<byte> csv,
        CsvOptions<byte>? options = null,
        CsvParallelOptions parallelOptions = default
    )
    {
        return AsAsyncEnumerableCore(
            ParallelReader.Create(csv, options ?? CsvOptions<byte>.Default),
            ValueProducer<byte, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="csv"/>.
    /// </summary>
    /// <param name="csv">CSV data to read</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IEnumerable<ReadOnlySpan<TValue>> Read<[DAM(Messages.ReflectionBound)] TValue>(
        ReadOnlyMemory<byte> csv,
        CsvOptions<byte>? options = null,
        CsvParallelOptions parallelOptions = default
    )
    {
        return AsEnumerableCore(
            ParallelReader.Create(csv, options ?? CsvOptions<byte>.Default),
            ValueProducer<byte, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="path"/>.
    /// </summary>
    /// <param name="path">Stream to read the CSV data from</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    [OverloadResolutionPriority(1000)] // prefer byte overload for file
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadFromFileAsync<[DAM(Messages.ReflectionBound)] TValue>(
        string path,
        CsvOptions<byte>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        ioOptions = ioOptions.ForFileIO();
        return AsAsyncEnumerableCore(
            ParallelReader.Create(CsvReader.GetFileStream(path, isAsync: true, in ioOptions), options ?? CsvOptions<byte>.Default, ioOptions),
            ValueProducer<byte, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="stream"/>.
    /// </summary>
    /// <param name="stream">Stream to read the CSV data from</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadAsync<[DAM(Messages.ReflectionBound)] TValue>(
        Stream stream,
        CsvOptions<byte>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(stream);
        if (!stream.CanRead) FlameCsv.Extensions.Throw.StreamNotReadable(stream);
        return AsAsyncEnumerableCore(
            ParallelReader.Create(stream, options ?? CsvOptions<byte>.Default, ioOptions),
            ValueProducer<byte, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="path"/>.
    /// </summary>
    /// <param name="path">Stream to read the CSV data from</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    [OverloadResolutionPriority(1000)] // prefer byte overload for file
    public static IEnumerable<ReadOnlySpan<TValue>> ReadFromFile<[DAM(Messages.ReflectionBound)] TValue>(
        string path,
        CsvOptions<byte>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        ioOptions = ioOptions.ForFileIO();
        return AsEnumerableCore(
            ParallelReader.Create(CsvReader.GetFileStream(path, isAsync: false, in ioOptions), options ?? CsvOptions<byte>.Default, ioOptions),
            ValueProducer<byte, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="stream"/>.
    /// </summary>
    /// <param name="stream">Stream to read the CSV data from</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    [RUF(Messages.Reflection), RDC(Messages.DynamicCode)]
    public static IEnumerable<ReadOnlySpan<TValue>> Read<[DAM(Messages.ReflectionBound)] TValue>(
        Stream stream,
        CsvOptions<byte>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(stream);
        if (!stream.CanRead) FlameCsv.Extensions.Throw.StreamNotReadable(stream);
        return AsEnumerableCore(
            ParallelReader.Create(stream, options ?? CsvOptions<byte>.Default, ioOptions),
            ValueProducer<byte, TValue>.Create(options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="csv"/>.
    /// </summary>
    /// <param name="csv">CSV data to read</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadAsync<TValue>(
        ReadOnlyMemory<char> csv,
        CsvTypeMap<char, TValue> typeMap,
        CsvOptions<char>? options = null,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(typeMap);

        return AsAsyncEnumerableCore(
            ParallelReader.Create(csv, options ?? CsvOptions<char>.Default),
            ValueProducer<char, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="csv"/>.
    /// </summary>
    /// <param name="csv">CSV data to read</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IEnumerable<ReadOnlySpan<TValue>> Read<TValue>(
        ReadOnlyMemory<char> csv,
        CsvTypeMap<char, TValue> typeMap,
        CsvOptions<char>? options = null,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(typeMap);

        return AsEnumerableCore(
            ParallelReader.Create(csv, options ?? CsvOptions<char>.Default),
            ValueProducer<char, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="path"/>.
    /// </summary>
    /// <param name="path">TextReader to read the CSV data from</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="encoding">Encoding to use, defaults to UTF8</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadFromFileAsync<TValue>(
        string path,
        CsvTypeMap<char, TValue> typeMap,
        Encoding? encoding = null,
        CsvOptions<char>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        ArgumentNullException.ThrowIfNull(typeMap);

        ioOptions = ioOptions.ForFileIO();
        return AsAsyncEnumerableCore(
            ParallelReader.Create(CsvReader.GetFileStream(path, isAsync: true, in ioOptions), encoding, options ?? CsvOptions<char>.Default, ioOptions),
            ValueProducer<char, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="reader"/>.
    /// </summary>
    /// <param name="reader">TextReader to read the CSV data from</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadAsync<TValue>(
        TextReader reader,
        CsvTypeMap<char, TValue> typeMap,
        CsvOptions<char>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(reader);
        ArgumentNullException.ThrowIfNull(typeMap);

        return AsAsyncEnumerableCore(
            ParallelReader.Create(reader, options ?? CsvOptions<char>.Default, ioOptions),
            ValueProducer<char, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="path"/>.
    /// </summary>
    /// <param name="path">TextReader to read the CSV data from</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="encoding">Encoding to use, defaults to UTF8</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IEnumerable<ReadOnlySpan<TValue>> ReadFromFile<TValue>(
        string path,
        CsvTypeMap<char, TValue> typeMap,
        Encoding? encoding = null,
        CsvOptions<char>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        ArgumentNullException.ThrowIfNull(typeMap);

        ioOptions = ioOptions.ForFileIO();
        return AsEnumerableCore(
            ParallelReader.Create(CsvReader.GetFileStream(path, isAsync: false, in ioOptions), encoding, options ?? CsvOptions<char>.Default, ioOptions),
            ValueProducer<char, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="reader"/>.
    /// </summary>
    /// <param name="reader">TextReader to read the CSV data from</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IEnumerable<ReadOnlySpan<TValue>> Read<TValue>(
        TextReader reader,
        CsvTypeMap<char, TValue> typeMap,
        CsvOptions<char>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(reader);
        ArgumentNullException.ThrowIfNull(typeMap);

        return AsEnumerableCore(
            ParallelReader.Create(reader, options ?? CsvOptions<char>.Default, ioOptions),
            ValueProducer<char, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="csv"/>.
    /// </summary>
    /// <param name="csv">CSV data to read</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadAsync<TValue>(
        ReadOnlyMemory<byte> csv,
        CsvTypeMap<byte, TValue> typeMap,
        CsvOptions<byte>? options = null,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(typeMap);

        return AsAsyncEnumerableCore(
            ParallelReader.Create(csv, options ?? CsvOptions<byte>.Default),
            ValueProducer<byte, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="csv"/>.
    /// </summary>
    /// <param name="csv">CSV data to read</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IEnumerable<ReadOnlySpan<TValue>> Read<TValue>(
        ReadOnlyMemory<byte> csv,
        CsvTypeMap<byte, TValue> typeMap,
        CsvOptions<byte>? options = null,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(typeMap);

        return AsEnumerableCore(
            ParallelReader.Create(csv, options ?? CsvOptions<byte>.Default),
            ValueProducer<byte, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="path"/>.
    /// </summary>
    /// <param name="path">Stream to read the CSV data from</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadFromFileAsync<TValue>(
        string path,
        CsvTypeMap<byte, TValue> typeMap,
        CsvOptions<byte>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        ArgumentNullException.ThrowIfNull(typeMap);

        ioOptions = ioOptions.ForFileIO();
        return AsAsyncEnumerableCore(
            ParallelReader.Create(CsvReader.GetFileStream(path, isAsync: true, in ioOptions), options ?? CsvOptions<byte>.Default, ioOptions),
            ValueProducer<byte, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="stream"/>.
    /// </summary>
    /// <param name="stream">Stream to read the CSV data from</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IAsyncEnumerable<ReadOnlyMemory<TValue>> ReadAsync<TValue>(
        Stream stream,
        CsvTypeMap<byte, TValue> typeMap,
        CsvOptions<byte>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(stream);
        if (!stream.CanRead) FlameCsv.Extensions.Throw.StreamNotReadable(stream);
        ArgumentNullException.ThrowIfNull(typeMap);

        return AsAsyncEnumerableCore(
            ParallelReader.Create(stream, options ?? CsvOptions<byte>.Default, ioOptions),
            ValueProducer<byte, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="path"/>.
    /// </summary>
    /// <param name="path">Stream to read the CSV data from</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IEnumerable<ReadOnlySpan<TValue>> ReadFromFile<TValue>(
        string path,
        CsvTypeMap<byte, TValue> typeMap,
        CsvOptions<byte>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        ArgumentNullException.ThrowIfNull(typeMap);

        ioOptions = ioOptions.ForFileIO();
        return AsEnumerableCore(
            ParallelReader.Create(CsvReader.GetFileStream(path, isAsync: false, in ioOptions), options ?? CsvOptions<byte>.Default, ioOptions),
            ValueProducer<byte, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

    /// <summary>
    /// Parses CSV records from the CSV data <paramref name="stream"/>.
    /// </summary>
    /// <param name="stream">Stream to read the CSV data from</param>
    /// <param name="typeMap">Type map used to bind the CSV data</param>
    /// <param name="options">Options to use, <see cref="CsvOptions{T}.Default"/> used by default</param>
    /// <param name="ioOptions">Options to configure the buffer size and other IO related options</param>
    /// <param name="parallelOptions">
    /// Options to configure batch size, cancellation, and other parallelization settings.
    /// </param>
    /// <returns>
    /// An enumerable that parses unordered batches of <typeparam name="TValue"/> from the CSV data.
    /// The yielded batches <strong>must not</strong> be used after the enumeration continues or stops.
    /// </returns>
    public static IEnumerable<ReadOnlySpan<TValue>> Read<TValue>(
        Stream stream,
        CsvTypeMap<byte, TValue> typeMap,
        CsvOptions<byte>? options = null,
        CsvIOOptions ioOptions = default,
        CsvParallelOptions parallelOptions = default
    )
    {
        ArgumentNullException.ThrowIfNull(stream);
        if (!stream.CanRead) FlameCsv.Extensions.Throw.StreamNotReadable(stream);
        ArgumentNullException.ThrowIfNull(typeMap);

        return AsEnumerableCore(
            ParallelReader.Create(stream, options ?? CsvOptions<byte>.Default, ioOptions),
            ValueProducer<byte, TValue>.Create(typeMap, options, parallelOptions),
            parallelOptions
        );
    }

}
