name: Publish to NuGet

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and publish from'
        required: true
        default: 'main'
      version:
        description: 'Package version (leave empty to use version from csproj)'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build src/Core/FlameCsv.Core.csproj --configuration Release --no-restore
      
    - name: Set version (if provided)
      if: ${{ github.event.inputs.version != '' }}
      run: |
        dotnet pack src/Core/FlameCsv.Core.csproj --configuration Release --no-build --output nupkgs /p:Version=${{ github.event.inputs.version }}
      
    - name: Create package (using project version)
      if: ${{ github.event.inputs.version == '' }}
      run: dotnet pack src/Core/FlameCsv.Core.csproj --configuration Release --no-build --output nupkgs
      
    - name: Publish to NuGet
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
